- name: Create directory structure
  ansible.builtin.file:
    path: '{{ nerc_nrpe_prefix }}/etc/ssl'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: directory

- name: Install NRPE config and ssl files
  ansible.builtin.template:
    src: 'templates/{{ item.path }}.j2'
    dest: '{{ nerc_nrpe_prefix }}/{{ item.path }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  notify: Restart Nagios
  loop:
    - { path: 'etc/ssl.cfg',
        owner: 'root',
        group: 'root',
        mode: '0644' }
    - { path: 'etc/ssl/nrpe-ca-cert.pem',
        owner: 'root',
        group: 'root',
        mode: '0644' }
    - { path: 'etc/ssl/nrpe-cert.pem',
        owner: 'root',
        group: 'root',
        mode: '0644' }
    - { path: 'etc/ssl/nrpe-key.pem',
        owner: 'root',
        group: 'root',
        mode: '0644' }
